<!DOCTYPE html>
<html>
    <head>
        <title>Physically Plausible Animation of Human Upper Body from a Single Image Visualization</title>
        <style>
            table, th, td {
              border: 1px solid black;
              border-collapse: collapse;
              table-layout:fixed;
            }
/*            h1 {text-align: center;}
            div {text-align: center;}*/
        </style>
    </head>
    <body>
            <h1>Physically Plausible Animation of Human Upper Body from a Single Image Visualization</h1>
            <div style="width: 50%;">
            Frame by frame evaluation result of Physically Plausible Animation of Human Upper Body from a Single Image (Ours), <a href="https://vision.cornell.edu/se3/wp-content/uploads/2018/03/1575.pdf">Controllable Video Generation with Sparse Trajectories</a>(Hao et al.), 3D Simulation, and <a href="https://xbpeng.github.io/projects/SFV/index.html">Motion Reconstruction Code and Data for Skills from Videos</a> (SFV). For each sample, the top-left frame is the ground truth video. All methods aim to generate a video in which the person’s wrists move along the ground-truth wrist trajectories. The top-second-to-last videos are the synthesized videos generated by our method, Hao et al., 3D simulation, SfV respectively. The bottom-left video overlays the predicted poses generates by our method over our result. The other bottom videos show the per-pixel PSNR values of the top corresponding method as heatmaps. For PSNR, higher is better. For LPIPS, lower is better. Our results generally look more plausible and sharper than the baselines’, as reflected by LPIPS. However, the misalignment of the head and arms in our results lead to a worse PSNR score than the blurry results of Hao et al.'s method. Note that SfV requires the whole ground truth video as the input for training, while other method only takes the first frame and the 2D wrist trajectories of the ground truth video as input. 
            </div>
            <h3>Total Result</h3>
            <table width="50%" style="text-align:center">
                <tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th>
                </tr><tr>
                    <td> PSNR </td><td> 22.633 </td><td> 24.308 </td><td> 21.230 </td><td> 22.227 </td>
                </tr>
                <tr>
                    <td> LPIPS </td><td> 0.121 </td><td> 0.134 </td><td> 0.160 </td><td> 0.130 </td>
                </tr>
            </tbody></table>
            <!--<script language="javascript" type="text/javascript">
                var baseurl = "src/"
                // var baseurl = "./src/"
                
                // create table
                var samplenum = 19;
                
                for (var i=0; i < samplenum; i++) {
                    document.write("<h3>sample " + (i + 1).toString() + "</h3>")

                    document.write("<table>");
                    document.write("<td><video width='1400' height='600' controls><source src='" +baseurl+"samples/output"+(i).toString()+".mp4'></video></td>");
                    // document.write("</table>");

                    // document.write("<table width=50% style='text-align:center'>");
                    // document.write("<th>Method</th><th>PSNR</th><th>SSIM</th><th>LPIPS</th>")
                    // document.write("<tr>");
                    // document.write("<td> 2D baseline </td>")
                    // document.write("<td id=controllable_" + (i * 3).toString() + "></td>");
                    // document.write("<td id=controllable_" + (i * 3 + 1).toString() + "></td>");
                    // document.write("<td id=controllable_" + (i * 3 + 2).toString() + "></td>");
                    // document.write("</tr>");
                    
                    // document.write("</br>")

                    // document.write("<tr>");
                    // document.write("<td> Ours </td>")
                    // document.write("<td id=pp_" + (i * 3).toString() + "></td>");
                    // document.write("<td id=pp_" + (i * 3 + 1).toString() + "></td>");
                    // document.write("<td id=pp_" + (i * 3 + 2).toString() + "></td>");
                    // document.write("</tr>");
                    // document.write("</table>");

                    document.write("<table width=50% style='text-align:center'>");
                    document.write("<th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th>")
                    document.write("<tr>");
                    document.write("<td> PSNR </td>")
                    document.write("<td id=pp_" + (i * 3).toString() + "></td>");
                    document.write("<td id=2d_" + (i * 3).toString() + "></td>");
                    document.write("</tr>");
                    
                    document.write("</br>")

                    document.write("<tr>");
                    document.write("<td> LPIPS </td>")
                    document.write("<td id=pp_" + (i * 3 + 2).toString() + "></td>");
                    document.write("<td id=2d_" + (i * 3 + 2).toString() + "></td>");
                    document.write("</tr>");
                    document.write("</table>");

                    document.write("</br>")
                }
                document.write("</table>");
            
                function write_controllable_content(){
                    if(controllable_reader.readyState==4){
                        controllable_result = controllable_reader.responseText.split(" ");
                        console.log(controllable_result.length);
                        for (var i=0; i < controllable_result.length - 1; i++){
                            if(i % 3 != 1){
                                element = document.getElementById("2d_" + i.toString());
                                controllable_result[i] = parseFloat(controllable_result[i]).toFixed(3).toString();
                                element.innerHTML = controllable_result[i];
                            }
                        }
                    }
                }
                function write_pp_content(){
                    if(pp_reader.readyState==4){
                        pp_result = pp_reader.responseText.split(" ");
                        for (var i=0; i < pp_result.length - 1; i++){
                            if (i % 3 != 1){
                                element = document.getElementById("pp_" + i.toString());
                                pp_result[i] = parseFloat(pp_result[i]).toFixed(3).toString();
                                element.innerHTML = pp_result[i];
                            }
                        }
                    }
                }

                // write controllable file
                var controllable_txt = baseurl + "2d_result.txt";
                // var controllable_txt = "src/control_result.txt";
                var controllable_reader = new XMLHttpRequest() || new ActiveXObject('MSXML2.XMLHTTP');
                controllable_reader.open('get', controllable_txt, true); 
                controllable_reader.onreadystatechange = write_controllable_content;
                controllable_reader.send(null);
                
                // write pp file
                var pp_txt = baseurl + "ours_result.txt";
                // var pp_txt = "src/ours_result.txt";
                var pp_reader = new XMLHttpRequest() || new ActiveXObject('MSXML2.XMLHTTP');
                pp_reader.open('get', pp_txt, true); 
                pp_reader.onreadystatechange = write_pp_content;
                pp_reader.send(null);-->



            </script><h3>sample 1</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample0.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>24.117</td><td>25.619</td><td>21.463</td><td>22.517</td></tr><tr><td> LPIPS </td><td>0.079</td><td>0.083</td><td>0.133</td><td>0.099</td></tr></tbody></table>
            <br><h3>sample 2</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample1.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>23.116</td><td>23.673</td><td>20.828</td><td>20.442</td></tr><tr><td> LPIPS </td><td>0.104</td><td>0.141</td><td>0.184</td><td>0.166</td></tr></tbody></table>
            <br><h3>sample 3</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample2.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>21.486</td><td>22.566</td><td>19.655</td><td>22.813</td></tr><tr><td> LPIPS </td><td>0.131</td><td>0.162</td><td>0.213</td><td>0.113</td></tr></tbody></table>
            <br><h3>sample 4</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample3.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>21.986</td><td>22.403</td><td>22.154</td><td>21.828</td></tr><tr><td> LPIPS </td><td>0.192</td><td>0.172</td><td>0.149</td><td>0.197</td></tr></tbody></table>
            <br><h3>sample 5</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample4.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>22.710</td><td>23.691</td><td>21.622</td><td>22.354</td></tr><tr><td> LPIPS </td><td>0.106</td><td>0.134</td><td>0.146</td><td>0.126</td></tr></tbody></table>
            <br><h3>sample 6</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample5.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>22.976</td><td>22.749</td><td>22.089</td><td>21.699</td></tr><tr><td> LPIPS </td><td>0.121</td><td>0.180</td><td>0.145</td><td>0.166</td></tr></tbody></table>
            <br><h3>sample 7</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample6.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>23.961</td><td>24.119</td><td>21.612</td><td>22.762</td></tr><tr><td> LPIPS </td><td>0.100</td><td>0.137</td><td>0.136</td><td>0.096</td></tr></tbody></table>
            <br><h3>sample 8</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample7.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>23.351</td><td>27.503</td><td>21.767</td><td>22.388</td></tr><tr><td> LPIPS </td><td>0.101</td><td>0.090</td><td>0.133</td><td>0.120</td></tr></tbody></table>
            <br><h3>sample 9</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample8.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>23.388</td><td>27.517</td><td>20.788</td><td>23.343</td></tr><tr><td> LPIPS </td><td>0.084</td><td>0.053</td><td>0.160</td><td>0.086</td></tr></tbody></table>
            <br><h3>sample 10</h3><table><tbody><tr><td><video width="1400" height="600" controls=""><source src="src/samples/sample9.mp4"></video></td></tr></tbody></table><br><table width="50%" style="text-align:center"><tbody><tr><th>Method</th><th>Ours</th><th>Hao et al.</th><th>3D Simulation</th><th>SfV</th></tr><tr><td> PSNR </td><td>22.848</td><td>23.842</td><td>21.252</td><td>22.118</td></tr><tr><td> LPIPS </td><td>0.104</td><td>0.146</td><td>0.154</td><td>0.130</td></tr></tbody></table>
    </body>
</html>
